[package]
name = "impulse-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.4"
basedrop = "0.1.2"
cpal = "0.15.3"
enumflags2 = "0.7.9"
# grid = "0.13.0"
left-right = "0.11.5"
#nom = "7.1.3"
# toodee = { version="0.5.0", default-features=false }
